version: "3.9"
services:
  web:
    build: ./apps/web
    command: pnpm dev
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    depends_on:
      - renderer
      - dispatcher
  renderer:
    build: ./services/renderer
    command: pnpm dev
    env_file:
      - ./.env
    ports:
      - "4000:4000"
  dispatcher:
    build: ./services/dispatcher
    command: pnpm dev
    env_file:
      - ./.env
    ports:
      - "4100:4100"
